[tools]
age = "latest"
atuin = {
  version = "latest",
  postinstall = '''
  mkdir ~/.local/share/atuin
  atuin init nu | save ~/.local/share/atuin/init.nu   
  '''
}
bat = "latest"
carapace = {
  version = "latest",
  postinstall = '''
  $env.CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense'
  mkdir $"($nu.cache-dir)"
  carapace _carapace nushell | save --force $"($nu.cache-dir)/carapace.nu"
  '''
}
crush = "latest"
dua = "latest"
fnox = "latest"
fzf = { version = "latest", postinstall = "fzf --nushell | save -f ($nu.data-dir | path join vendor autoload _fzf_integration.nu)" }
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
gsudo = "latest"
gum = "latest"
helix = "latest"
"github:herdrdev/herdr" = "latest"
hunk = "latest"
node = "latest"
npm = "latest"
oh-my-posh = { version = "latest", postinstall = "oh-my-posh init nu --config ~/.config/oh-my-posh/themes/mkolibaba.omp.yaml" }
pi = "latest"
python = "latest"
ripgrep = "latest"
sd = "latest"
sops = "latest"
yazi = "latest"
zellij = "latest"
zoxide = { version = "latest", postinstall = "zoxide init nushell | save -f ($nu.data-dir | path join vendor autoload zoxide.nu)" }

[env]
_.file = "~/.config/mise/secret.env"
EDITOR = "hx"
SHELL = "nu"
GITHUB_USERNAME = "mkolibaba"
SOPS_AGE_KEY_FILE = "~/.config/sops/age/keys.txt"

[bootstrap.packages]
"winget:voidtools.Everything" = "latest"
"winget:Microsoft.VisualStudioCode" = "latest"
"winget:Fork.Fork" = "latest"

[settings]
env_cache = true
env_cache_ttl = "72h"
windows_default_file_shell_args = "nu"
windows_default_inline_shell_args = "nu -c"
