theme = "dracula"

[editor]
shell = ["nu", "-c"]

[editor.auto-save]
after-delay.enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.file-picker]
hidden = false

[keys.normal]
C-y = [
  ':sh rm -f C:\unique-file',
  ':insert-output yazi.exe %{buffer_name} --chooser-file=C:\unique-file',
  ':open %sh{type C:\unique-file}',
  ':redraw',
]
