theme = "kanagawa"

[editor]
shell = ["nu", "-c"]

[editor.auto-save]
after-delay.enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.file-picker]
hidden = false
