theme = "dracula"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
shell = ["nu", "-c"]
end-of-line-diagnostics = "hint"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 2000

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-y = [
  ':sh rm -f C:\unique-file',
  ':insert-output yazi.exe %{buffer_name} --chooser-file=C:\unique-file',
  ':open %sh{type C:\unique-file}',
  ':redraw',
]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"S-ret" = "goto_word"
"ret" = "repeat_last_motion"
